# Generated by Django 4.2.3 on 2023-07-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=500)),
                ('emEstoque', models.BooleanField()),
                ('preco', models.IntegerField()),
                ('data_lanc', models.DateField()),
                ('slug', models.SlugField()),
                ('foto', models.ImageField(upload_to='imagens/%Y/%m/%D')),
            ],
        ),
    ]
