# Generated by Django 4.2.3 on 2023-07-13 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fender', '0002_tipo_estilo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tipo',
            new_name='TipoFender',
        ),
    ]
